12_Django/Level_5/first_project/first_app/urls.py
from django.conf.urls import url
from first_app import views

app_name = 'first_app'

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^user-login/$', views.user_login, name='user-login'),
]

12_Django/Level_5/first_project/first_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from first_app import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^first-app/', include('first_app.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
]

12_Django/Level_5/first_project/first_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User)
    profile_picture = models.ImageField(upload_to='profile-pictures', blank=True)
    portfolio_site = models.URLField(blank=True)

    def __str__(self):
        return self.user.username

12_Django/Level_5/first_project/first_app/forms.py
from django import forms
from django.contrib.auth.models import User
from first_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_picture')

12_Django/Level_5/first_project/first_app/views.py
from django.shortcuts import render
from first_app.forms import UserForm, UserProfileInfoForm
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout


def index(request):
    return render(request, 'first_app/index.html')


def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            # SAVE USER
            user = user_form.save()
            # HASH PASSWORD
            user.set_password(user.password)
            # SAVE CHANGES FOR HASHED PASSWORD
            user.save(0)

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_picture' in request.FILES:
                profile.profile_picture = request.FILES['profile_picture']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'first_app/registration.html', {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})


def user_login(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse("index"))
            else:
                return HttpResponse("User is not active")
        else:
            print("Access failed. Username: {} Password: {}".format(
                username, password))
    else:
        return render(request, 'first_app/login.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))

12_Django/Level_5/first_project/templates/first_app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Django Level 5 - Users</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li>
                    <a href="{% url 'index' %}" class="navbar-brand">Home</a>
                </li>
                <li>
                    <a href="{% url 'admin:index' %}" class="navbar-link">Admin</a>
                </li>
                <li>
                    <a href="{% url 'first_app:register' %}" class="navbar-link">Register</a>
                </li>
                {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'logout' %}" class="navbar-link">Logout</a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'first_app:user-login' %}" class="navbar-link">Login</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block content %} {% endblock %}
    </div>
</body>

</html>

12_Django/Level_5/first_project/templates/first_app/index.html
{% extends "first_app/base.html" %}

{% block content %}

<div class="jumbotron">
    <h1>Django Level Five</h1>
</div>

{% endblock %}

12_Django/Level_5/first_project/templates/first_app/login.html
{% extends "first_app/base.html" %} {% block content %}

<div class="jumbotron">
    <h1>Login</h1>
    <form action="{% url 'first_app:user-login' %}" method="post">
        {% csrf_token %}
        
        <label for="username">User Name:</label>
        <input type="text" name="username">
        <br>
        <label for="password">Password:</label>
        <input type="password" name="password">
        <br>
        <input type="submit" value="Login">
    </form>
</div>

{% endblock %}

12_Django/Level_5/first_project/templates/first_app/registration.html
{% extends "first_app/base.html" %} {% load staticfiles %} {% block content %}

<div class="jumbotron">
    {% if registered %}
        <h1>Thank you for registering!</h1>
    {% else %}
        <h1>Register here</h1>
        <h3>Fill out the form:</h3>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" value="Register">
        </form>
    {% endif %}
</div>

{% endblock %}